name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  lambda-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        working-directory: ./vehicle-lambda
        run: npm install
      - name: Build Lambda function
        working-directory: ./vehicle-lambda
        run: npm run build
      - name: Upload Lambda bundle
        uses: actions/upload-artifact@v4
        with:
          name: lambda-dist
          path: terraform/dist/index.js
      - name: Install Emergency Lambda dependencies
        working-directory: ./emergency-lambda
        run: npm install
      - name: Build Emergency Lambda function
        working-directory: ./emergency-lambda
        run: npm run build
      - name: Upload Emergency Lambda bundle
        uses: actions/upload-artifact@v4
        with:
          name: emergency-lambda-dist
          path: terraform/dist/emergency-lambda.js
  destroy:
    needs: lambda-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Download Lambda bundle
        uses: actions/download-artifact@v4
        with:
          name: lambda-dist
          path: terraform/dist
      - name: Download Emergency Lambda bundle
        uses: actions/download-artifact@v4
        with:
          name: emergency-lambda-dist
      - run: terraform init
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: terraform destroy -auto-approve
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
